package entity;
// Generated 06/02/2021 21:10:06 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Movimiento generated by hbm2java
 */
@Entity
@Table (name = "movimiento")
public class Movimiento  implements java.io.Serializable {

    @Id @GeneratedValue
    @Column (name = "idMovimiento")
    private Integer idMovimiento;
    
    @Column (name = "idPartida")
    private Partida partida;
    
    @Column (name = "turno")
    private String turnode;
    
    @Column (name = "fila")
    private int fila;
    
    @Column (name = "columna")
    private int columna;

    public Movimiento() {
    }

    public Movimiento(Partida partida, String turnode, int fila, int columna) {
       this.partida = partida;
       this.turnode = turnode;
       this.fila = fila;
       this.columna = columna;
    }
   
    public Integer getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(Integer idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public String getTurnode() {
        return this.turnode;
    }
    
    public void setTurnode(String turnode) {
        this.turnode = turnode;
    }
    public int getFila() {
        return this.fila;
    }
    
    public void setFila(int fila) {
        this.fila = fila;
    }
    public int getColumna() {
        return this.columna;
    }
    
    public void setColumna(int columna) {
        this.columna = columna;
    }




}


