
CREATE TABLE PRODUCTE (
 ID		SMALLINT(4)  NOT NULL PRIMARY KEY,
 DESCRIPCIO	VARCHAR(50),
 STOCKACTUAL	TINYINT(3),
 STOCKMINIM	TINYINT(3),
 PVP		FLOAT(6,2)
);

INSERT INTO PRODUCTE VALUES (1, 'Pulpo reversible azul', 8, 3, 30);
INSERT INTO PRODUCTE VALUES (2, 'Pulpo reversible rojo', 7, 6, 60);
INSERT INTO PRODUCTE VALUES (3, 'Pulpo reversible rosa', 7, 9, 90);
INSERT INTO PRODUCTE VALUES (4, 'Pulpo reversible lila', 8, 12, 120);

CREATE TABLE VENDES (
 ID    		SMALLINT(4)  NOT NULL PRIMARY KEY,
 IDPRODUCTE	SMALLINT(4) NOT NULL REFERENCES producte(ID),
 DATAVENDA	DATE,
 QUANTITAT	TINYINT(3)
);

CREATE TABLE COMANDES (
 ID    		SMALLINT(4)  NOT NULL PRIMARY KEY,
 IDPRODUCTE	SMALLINT(4) NOT NULL REFERENCES producte(ID),
 DATACOMANDA	DATE,
 QUANTITAT	TINYINT(3)
);
