/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m6_uf2_act1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ianlo
 */
public class M6_uf2_act1_InserirMenuAlumne extends javax.swing.JFrame {

    /**
     * Creates new form M6_uf2_act1_InserirAlumne
     */
    public M6_uf2_act1_InserirMenuAlumne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonTorna = new javax.swing.JButton();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldAdrecaPostal = new javax.swing.JTextField();
        jTextFieldNaixement = new javax.swing.JTextField();
        jTextFieldCodiPostal = new javax.swing.JTextField();
        jTextFieldSexe = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jLabelNaixement = new javax.swing.JLabel();
        jLabelAdrecaPostal = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelCodiPostal = new javax.swing.JLabel();
        jButtonGuarda = new javax.swing.JButton();
        jTextFieldDni = new javax.swing.JTextField();
        jLabelNoExisteix = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSalir.setText("X");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));

        jButtonTorna.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTorna.setText("←");
        jButtonTorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTorna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDni.setText("DNI");
        jPanel1.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 160, 20));

        jTextFieldNom.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 140, -1));

        jTextFieldAdrecaPostal.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldAdrecaPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAdrecaPostalActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAdrecaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 140, -1));

        jTextFieldNaixement.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldNaixement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNaixementActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNaixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, -1));

        jTextFieldCodiPostal.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldCodiPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 140, -1));

        jTextFieldSexe.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 140, -1));

        jLabelNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNom.setText("Nom");
        jPanel1.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, 20));

        jLabelNaixement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNaixement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNaixement.setText("Naixement (yyyy-mm-dd)");
        jPanel1.add(jLabelNaixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 160, 20));

        jLabelAdrecaPostal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAdrecaPostal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAdrecaPostal.setText("Adreça Postal");
        jPanel1.add(jLabelAdrecaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 160, 20));

        jLabelSexe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSexe.setText("Sexe (H/M)");
        jPanel1.add(jLabelSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, 20));

        jLabelCodiPostal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodiPostal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCodiPostal.setText("Codi Postal");
        jPanel1.add(jLabelCodiPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 160, 20));

        jButtonGuarda.setText("Guardar");
        jButtonGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGuarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTextFieldDni.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 140, -1));

        jLabelNoExisteix.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelNoExisteix.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelNoExisteix, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 190, 310, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonTornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTornaActionPerformed
        // TODO add your handling code here:
        M6_uf2_act1_InserirMenu tornaInserirMenu = new M6_uf2_act1_InserirMenu();
        tornaInserirMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTornaActionPerformed

    private void jTextFieldAdrecaPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAdrecaPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAdrecaPostalActionPerformed

    private void jTextFieldNaixementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNaixementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNaixementActionPerformed

    private void jButtonGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardaActionPerformed
        // TODO add your handling code here:
        ResultSet comparaStmt;
        Statement stmt = null;
        Statement stmtInsert = null;
        M6_uf2_act1 connexio = new M6_uf2_act1();
        
        if (!jTextFieldNom.getText().equals("") && !jTextFieldDni.getText().equals("") && !jTextFieldNaixement.getText().equals("") && !jTextFieldAdrecaPostal.getText().equals("")
                && !jTextFieldSexe.getText().equals("") && !jTextFieldCodiPostal.getText().equals("")){
            try {
            
                connexio.conexion();
                stmt = connexio.conexion().createStatement();
                comparaStmt = stmt.executeQuery("SELECT codipostal FROM poblacions WHERE codipostal = '" + jTextFieldCodiPostal.getText() + "'");

                if(comparaStmt.next()){
                    stmtInsert = connexio.conexion().createStatement();
                    stmtInsert.execute("INSERT INTO alumnes VALUES ('" + jTextFieldNom.getText() + "','" + jTextFieldDni.getText() + "','" + jTextFieldNaixement.getText() + "','" 
                            + jTextFieldAdrecaPostal.getText() + "','" + jTextFieldSexe.getText() + "'," + jTextFieldCodiPostal.getText() + ")");
                } else {
                    jLabelNoExisteix.setText("Aquest codi postal no correspon a cap població");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabelNoExisteix.setText("Falten camps per omplir");
        }
        vaciar();
    }//GEN-LAST:event_jButtonGuardaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        vaciar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public void vaciar(){
        jTextFieldAdrecaPostal.setText("");
        jTextFieldCodiPostal.setText("");
        jTextFieldDni.setText("");
        jTextFieldNaixement.setText("");
        jTextFieldNom.setText("");
        jTextFieldSexe.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M6_uf2_act1_InserirMenuAlumne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuarda;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTorna;
    private javax.swing.JLabel jLabelAdrecaPostal;
    private javax.swing.JLabel jLabelCodiPostal;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelNaixement;
    private javax.swing.JLabel jLabelNoExisteix;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldAdrecaPostal;
    private javax.swing.JTextField jTextFieldCodiPostal;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNaixement;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldSexe;
    // End of variables declaration//GEN-END:variables
}
