/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m6_uf2_act1;

/**
 *
 * @author ianlo
 */
public class M6_uf2_act1_InserirMenuAlumne extends javax.swing.JFrame {

    /**
     * Creates new form M6_uf2_act1_InserirAlumne
     */
    public M6_uf2_act1_InserirMenuAlumne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonTorna = new javax.swing.JButton();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jLabelNaixement = new javax.swing.JLabel();
        jLabelAdrecaPostal = new javax.swing.JLabel();
        jLabelSexe = new javax.swing.JLabel();
        jLabelCodiPostal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSalir.setText("X");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));

        jButtonTorna.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTorna.setText("←");
        jButtonTorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTorna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelDni.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDni.setText("DNI");
        jPanel1.add(jLabelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 20));

        jTextFieldNom.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 140, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 204));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 140, -1));

        jTextField4.setBackground(new java.awt.Color(255, 255, 204));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, -1));

        jTextField6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 140, -1));

        jLabelNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNom.setText("Nom");
        jPanel1.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 20));

        jLabelNaixement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNaixement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNaixement.setText("Naixement");
        jPanel1.add(jLabelNaixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 20));

        jLabelAdrecaPostal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAdrecaPostal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelAdrecaPostal.setText("Adreça Postal");
        jPanel1.add(jLabelAdrecaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 20));

        jLabelSexe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSexe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSexe.setText("Sexe");
        jPanel1.add(jLabelSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, 20));

        jLabelCodiPostal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodiPostal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCodiPostal.setText("Codi Postal");
        jPanel1.add(jLabelCodiPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 90, 20));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonTornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTornaActionPerformed
        // TODO add your handling code here:
        M6_uf2_act1_InserirMenu tornaInserirMenu = new M6_uf2_act1_InserirMenu();
        tornaInserirMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTornaActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuAlumne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M6_uf2_act1_InserirMenuAlumne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTorna;
    private javax.swing.JLabel jLabelAdrecaPostal;
    private javax.swing.JLabel jLabelCodiPostal;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelNaixement;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelSexe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
