/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m6_uf2_act1;

/**
 *
 * @author ianlo
 */
public class M6_uf2_act1_InserirMenu extends javax.swing.JFrame {

    /**
     * Creates new form M6_uf2_act1_InserirMenu
     */
    public M6_uf2_act1_InserirMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSallir = new javax.swing.JButton();
        jButtonTornar = new javax.swing.JButton();
        jButtonInserirAlumne = new javax.swing.JButton();
        jButtonInserirPoblacio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 250));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSallir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSallir.setText("X");
        jButtonSallir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSallirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSallir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));

        jButtonTornar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTornar.setText("←");
        jButtonTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButtonInserirAlumne.setText("Alumne");
        jButtonInserirAlumne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirAlumneActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInserirAlumne, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, 50));

        jButtonInserirPoblacio.setText("Població");
        jButtonInserirPoblacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPoblacioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInserirPoblacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSallirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSallirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSallirActionPerformed

    private void jButtonTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTornarActionPerformed
        // TODO add your handling code here:
        M6_uf2_act1_frame tornaFrame = new M6_uf2_act1_frame();
        tornaFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTornarActionPerformed

    private void jButtonInserirPoblacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPoblacioActionPerformed
        // TODO add your handling code here:
        M6_uf2_act1_InserirMenuPoblacio inserirPoblacio = new M6_uf2_act1_InserirMenuPoblacio();
        inserirPoblacio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInserirPoblacioActionPerformed

    private void jButtonInserirAlumneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirAlumneActionPerformed
        // TODO add your handling code here:
        M6_uf2_act1_InserirMenuAlumne inserirAlumne = new M6_uf2_act1_InserirMenuAlumne();
        inserirAlumne.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonInserirAlumneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M6_uf2_act1_InserirMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserirAlumne;
    private javax.swing.JButton jButtonInserirPoblacio;
    private javax.swing.JButton jButtonSallir;
    private javax.swing.JButton jButtonTornar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
