/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package m6_uf2_act1;

/**
 *
 * @author ianlo
 */
public class M6_uf2_act1_InserirMenuPoblacio extends javax.swing.JFrame {

    /**
     * Creates new form M6_uf2_act1_InserirMenuPoblacio
     */
    public M6_uf2_act1_InserirMenuPoblacio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelPoblacio = new javax.swing.JLabel();
        jLabelCodiPostal = new javax.swing.JLabel();
        jTextFieldPoblacio = new javax.swing.JTextField();
        jTextFieldCodiPostal = new javax.swing.JTextField();
        jButtonGuarda = new javax.swing.JButton();
        jButtonCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 40, 20));

        jButton2.setText("←");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelPoblacio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPoblacio.setText("Població");
        jPanel1.add(jLabelPoblacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 90, 20));

        jLabelCodiPostal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodiPostal.setText("Codi Postal");
        jPanel1.add(jLabelCodiPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 20));

        jTextFieldPoblacio.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(jTextFieldPoblacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 140, -1));

        jTextFieldCodiPostal.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldCodiPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodiPostalActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodiPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, -1));

        jButtonGuarda.setText("Guarda");
        jPanel1.add(jButtonGuarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 120, -1));

        jButtonCancela.setText("Cancela");
        jButtonCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 130, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        M6_uf2_act1_InserirMenu tornaInserirMenu = new M6_uf2_act1_InserirMenu();
        tornaInserirMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldCodiPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodiPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodiPostalActionPerformed

    private void jButtonCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelaActionPerformed
        // TODO add your handling code here:
        vaciar();
    }//GEN-LAST:event_jButtonCancelaActionPerformed

    public void vaciar(){
        jTextFieldCodiPostal.setText("");
        jTextFieldPoblacio.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuPoblacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuPoblacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuPoblacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(M6_uf2_act1_InserirMenuPoblacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new M6_uf2_act1_InserirMenuPoblacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCancela;
    private javax.swing.JButton jButtonGuarda;
    private javax.swing.JLabel jLabelCodiPostal;
    private javax.swing.JLabel jLabelPoblacio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodiPostal;
    private javax.swing.JTextField jTextFieldPoblacio;
    // End of variables declaration//GEN-END:variables
}
