package entity;
// Generated 28/01/2021 16:44:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private int idPartida;
     private String ganador;
     private Set movimientos = new HashSet(0);

    public Partida() {
    }

	
    public Partida(int idPartida, String ganador) {
        this.idPartida = idPartida;
        this.ganador = ganador;
    }
    public Partida(int idPartida, String ganador, Set movimientos) {
       this.idPartida = idPartida;
       this.ganador = ganador;
       this.movimientos = movimientos;
    }
   
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public String getGanador() {
        return this.ganador;
    }
    
    public void setGanador(String ganador) {
        this.ganador = ganador;
    }
    public Set getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set movimientos) {
        this.movimientos = movimientos;
    }




}


